DELETE FROM geometry_columns where f_table_name = 'admin_01234';
DELETE FROM geometry_columns where f_table_name = 'admin_5678';
DELETE FROM geometry_columns where f_table_name = 'admin_other';
DELETE FROM geometry_columns where f_table_name = 'buildings_lz';
DELETE FROM geometry_columns where f_table_name = 'buildings';
DELETE FROM geometry_columns where f_table_name = 'glaciers_text';
DELETE FROM geometry_columns where f_table_name = 'highway_area_casing';
DELETE FROM geometry_columns where f_table_name = 'highway_area_fill';
DELETE FROM geometry_columns where f_table_name = 'landcover_line';
DELETE FROM geometry_columns where f_table_name = 'landcover';
DELETE FROM geometry_columns where f_table_name = 'landuse_overlay';
DELETE FROM geometry_columns where f_table_name = 'minor_roads_casing';
DELETE FROM geometry_columns where f_table_name = 'minor_roads_fill';
DELETE FROM geometry_columns where f_table_name = 'placenames_capital';
DELETE FROM geometry_columns where f_table_name = 'placenames_large';
DELETE FROM geometry_columns where f_table_name = 'placenames_medium';
DELETE FROM geometry_columns where f_table_name = 'placenames_small';
DELETE FROM geometry_columns where f_table_name = 'polygon_barrier';
DELETE FROM geometry_columns where f_table_name = 'roads_text_name';
DELETE FROM geometry_columns where f_table_name = 'roads_text_ref_low_zoom';
DELETE FROM geometry_columns where f_table_name = 'roads_text_ref';
DELETE FROM geometry_columns where f_table_name = 'roads';
DELETE FROM geometry_columns where f_table_name = 'sports_grounds';
DELETE FROM geometry_columns where f_table_name = 'water_areas_overlay';
DELETE FROM geometry_columns where f_table_name = 'water_areas';
DELETE FROM geometry_columns where f_table_name = 'water_lines_casing';
DELETE FROM geometry_columns where f_table_name = 'water_lines_low_zoom';
DELETE FROM geometry_columns where f_table_name = 'water_lines';
INSERT INTO geometry_columns VALUES ('', 'public', 'admin_01234', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'admin_5678', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'admin_other', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'buildings_lz', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'buildings', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'glaciers_text', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'highway_area_casing', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'highway_area_fill', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'landcover_line', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'landcover', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'landuse_overlay', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'minor_roads_casing', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'minor_roads_fill', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'placenames_capital', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'placenames_large', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'placenames_medium', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'placenames_small', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'polygon_barrier', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'roads_text_name', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'roads_text_ref_low_zoom', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'roads_text_ref', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'roads', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'sports_grounds', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'water_areas_overlay', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'water_areas', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'water_lines_casing', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'water_lines_low_zoom', 'way', 2, 900913, 'GEOMETRY');
INSERT INTO geometry_columns VALUES ('', 'public', 'water_lines', 'way', 2, 900913, 'GEOMETRY');
